GET http://localhost:8080/v1/organization/{{organizationId}}/license/{{licenseId}}
Content-Type: application/json

###

POST http://localhost:8080/v1/organization/{{organizationId}}/license
Content-Type: application/json
Accept-Language: en

{
  "description": "Software product",
  "id": 54,
  "licenseId": "2",
  "licenseType": "full",
  "organizationId": "2",
  "productName": "Ostock"
}

###
PUT http://localhost:8080/v1/organization/{{organizationId}}/license
Content-Type: application/json
Accept-Language: en

{
  "description": "Software product",
  "id": 54,
  "licenseId": "2",
  "licenseType": "full",
  "organizationId": "2",
  "productName": "Ostock"
}

###
DELETE http://localhost:8080/v1/organization/{{organizationId}}/license/{{licenseId}}
Content-Type: application/json
Accept-Language: en